### ISSUE TITLE
Nested objects

### ISSUE THREAD

**Issue by Masynchin** [objectionary/phie#7]
This example not uses nested objects.

https://github.com/objectionary/phie/blob/101bdd079d6275a3ceebd3dbf612f456a3d2f546/src/bin/fibonacci.rs#L30-L42

Is it caused by parser limitations, or it is intentional (or both)? If yes is the answer to the first question, it may be caused by using regexp, which can not parse recursive structures. Am I right?

**Comment by Masynchin** [comment]
I have tried to compile the same example, but with one nested object instead of object reference.

~~~diff
ν0 ↦ ⟦ φ ↦ ν2 ⟧
ν1 ↦ ⟦ Δ ↦ 0x{:04X} ⟧
ν2 ↦ ⟦ φ ↦ ν3(ξ), 𝛼0 ↦ ν1 ⟧
- ν3 ↦ ⟦ φ ↦ ν13 ⟧
+ ν3 ↦ ⟦ φ ↦ ⟦ λ ↦ bool-if, ρ ↦ ν12, 𝛼0 ↦ ν7, 𝛼1 ↦ ν11 ⟧ ⟧
ν5 ↦ ⟦ Δ ↦ 0x0002 ⟧
ν6 ↦ ⟦ λ ↦ int-sub, ρ ↦ ξ.ξ.𝛼0, 𝛼0 ↦ ν5 ⟧
ν7 ↦ ⟦ Δ ↦ 0x0001 ⟧
ν8 ↦ ⟦ λ ↦ int-sub, ρ ↦ ξ.ξ.𝛼0, 𝛼0 ↦ ν7 ⟧
ν9 ↦ ⟦ φ ↦ ν3(ξ), 𝛼0 ↦ ν8 ⟧
ν10 ↦ ⟦ φ ↦ ν3(ξ), 𝛼0 ↦ ν6 ⟧
ν11 ↦ ⟦ λ ↦ int-add, ρ ↦ ν9, 𝛼0 ↦ ν10 ⟧
ν12 ↦ ⟦ λ ↦ int-less, ρ ↦ ξ.𝛼0, 𝛼0 ↦ ν5 ⟧
- ν13 ↦ ⟦ λ ↦ bool-if, ρ ↦ ν12, 𝛼0 ↦ ν7, 𝛼1 ↦ ν11 ⟧
~~~

It fails with:

~~~plain
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Can't split 'φ ↦ ⟦ λ ↦ bool-if' in two parts at '⟦ φ ↦ ⟦ λ ↦ bool-if, ρ ↦ ν12, 𝛼0 ↦ ν7, 𝛼1 ↦ ν11 ⟧ ⟧'"', src/emu.rs:90:72
~~~

If it is planned have nested objects, we can replace regexps with something more suitable, for example, [nom](https://crates.io/crates/nom) or [chumsky](https://crates.io/crates/chumsky).

**Comment by Masynchin** [comment]
@yegor256 can you take a look at this problem?

**Comment by yegor256** [comment]
@Masynchin the idea of phie is that we should NEVER have nested objects. all objects must be "flat".

**Comment by Masynchin** [comment]
@yegor256 maybe it is better to quote this:

> the idea of phie is that we should NEVER have nested objects. all objects must be "flat".

Because phi-calculus paper has example with nested objects (section 3.5)

~~~phi
x ↦ ⟦ y ↦ ⟦ z ↦ t ⟧ ⟧
~~~

Or maybe it is explicitly stated somewhere that there shouldn't be nested objects?

**Comment by yegor256** [comment]
@Masynchin the idea of this project is to work only after de-nesting of phi-expressions
